name: Docker Image CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag nest-shelter-donate-app:$(date +%s)
      - name: install
        run: npm install
      - name: unit test
        run: npm test
      - name: e2e test
        run: npm run test:e2e auth
        run: npm run test:e2e app
        run: npm run test:e2e wallet
