# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Tests

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  create-envfile:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:10.8
        env:
          DATABASE_URL: 'postgres://usr:pass@postgres:5432/db'
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'npm'
      - run: npm ci
      - run: npm install
      - run: npm i class-validator class-transformer
      - run: npm run test
